# Generated by Django 5.2.1 on 2025-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cuisine_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
