# Generated by Django 5.2.1 on 2025-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.CharField(max_length=255, unique=True)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('deal_type', models.CharField(max_length=255)),
                ('active_dates', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='telefoodpromos_photos/')),
                ('full_message_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('more_info_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
