# Generated by Django 5.2.1 on 2025-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpromotion',
            name='more_info_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
