# Generated by Django 5.2.1 on 2025-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_foodpromotion_more_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpromotion',
            name='active_dates',
            field=models.JSONField(default=list),
        ),
    ]
