# Generated by Django 5.2.1 on 2025-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_foodpromotion_active_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpromotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='telefoodpromos_photos/'),
        ),
    ]
